= Kuadrant Controller

image:https://github.com/Kuadrant/kuadrant-controller/actions/workflows/code-style.yaml/badge.svg[Code Style,link=https://github.com/Kuadrant/kuadrant-controller/actions/workflows/code-style.yaml] image:https://github.com/Kuadrant/kuadrant-controller/actions/workflows/testing.yaml/badge.svg[Testing,link=https://github.com/Kuadrant/kuadrant-controller/actions/workflows/testing.yaml] image:https://img.shields.io/badge/license-Apache--2.0-blue.svg[License,link=http://www.apache.org/licenses/LICENSE-2.0]

== Table of contents

* <<overview,Overview>>
* <<customresourcedefinitions,CustomResourceDefinitions>>
* <<list-of-features,List of features>>
* <<architecture,Architecture>>
* <<getting-started,xref:doc/getting-started.adoc[Getting started]>>
* <<user-guides,User Guides>>
 ** <<http-routing-rules-from-openapi-stored-in-a-configmap,xref:doc/service-discovery-oas-configmap.adoc[HTTP routing rules from OpenAPI stored in a configmap]>>
 ** <<http-routing-rules-from-openapi-served-by-the-service,xref:doc/service-discovery-oas-service.adoc[HTTP routing rules from OpenAPI served by the service]>>
 ** <<http-routing-rules-with-path-matching,xref:doc/service-discovery-path-match.adoc[HTTP routing rules with path matching]>>
 ** <<authn-based-on-api-key,xref:doc/authn-api-key.adoc[AuthN based on API key]>>
 ** <<authn-based-on-openid-connect,xref:doc/authn-oidc.adoc[AuthN based on OpenID Connect]>>
 ** <<rate-limiting,xref:doc/rate-limit.adoc[Rate limiting]>>
* <<contributing,Contributing>>
* <<licensing,Licensing>>

== Overview

Kuadrant is a re-architecture of API Management using Cloud Native concepts and separating the components to be less coupled, more reusable and leverage the underlying kubernetes platform.
It aims to deliver a smooth experience to providers and consumers of applications & services when it comes to rate limiting, authentication, authorization, discoverability, change management, usage contracts, insights, etc.

Kuadrant aims to produce a set of loosely coupled functionalities built directly on top of Kubernetes.
Furthermore it only strives to provide what Kubernetes doesn't offer out of the box, i.e.
Kuadrant won't be designing a new Gateway/proxy, instead it will opt to connect with what's there and what's being developed (think Envoy, GatewayAPI).

Kuadrant is a system of cloud-native k8s components that grows as users`' needs grow.

* From simple protection of a Service (via *AuthN*) that is used by teammates working on the same cluster, or "`sibling`" services, up to *AuthN* of users using OIDC plus custom policies.
* From no rate-limiting to rate-limiting for global service protection on to rate-limiting by users/plans

towards a full system that is more analogous to current API Management systems where business rules and plans define protections and Business/User related Analytics are available.

== CustomResourceDefinitions

A core feature of the kuadrant controller is to monitor the Kubernetes API server for changes to specific objects and ensure the owned k8s components configuration match these objects.
The kuadrant controller acts on the following https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/[CRDs]:

|===
| CRD | Description

| link:apis/networking/v1beta1/apiproduct_types.go[APIProduct]
| Customer-facing APIs.
APIProduct facilitates the creation of strong and simplified offerings for API consumers

| link:apis/networking/v1beta1/api_types.go[API]
| Internal APIs bundled in a product.
Kuadrant API objects grant API providers the freedom to map their internal API organization structure to kuadrant
|===

For a detailed description of the CRDs above, refer to the xref:doc/architecture.adoc[Architecture] page.

== List of features

|===
| Feature | Description | Stage

| https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md[OpenAPI 3.x]
| OpenAPI driven configuration.
The document can be read from a configmap or served from the upstream API service
| _Ready_

| _Path Match_ based routing
| HTTP routing rules will be configured based on request path expressions.
Accepted values are `Exact`, `Prefix` and `RegularExpression`
| _Ready_

| xref:doc/service-discovery.adoc[Service Discovery]
| kubernetes https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/[annotations] and https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/[labels] for a seamless integration
| _Ready_

| *AuthN* based on API key
| Protect your service with a simple API key based authentication mechanism
| _Ready_

| *AuthN* based on https://openid.net/connect/[OpenID Connect (OIDC)]
| Kuadrant can verify OIDC (JWTs) tokens to authenticate users
| _Ready_

| Global Rate Limiting
| Single global rate limit for all requests.
Main use case for protecting infrastructure resources
| _Ready_

| Rate Limiting Per Remote IP
| Rate limit configuration per each remote IP address.
Main use case for protecting infrastructure resources
| _Ready_

| Authenticated Rate Limiting
| Rate limit configuration per each authenticated client
| _Ready_

| Server TLS
| TLS termination for downstream connections
| Planned

| Upstream TLS
| Client certificates upstream connections
| Planned

| mTLS
| Mutual TLS termination for downstream connections
| Planned

| https://gateway-api.sigs.k8s.io/[Gateway API]
| Implementation of kuadrant features on top of the Gateway API
| Planned

| Monitoring and Alerting
| Observability based on https://grafana.com/[Grafana] and https://prometheus.io/[Prometheus]
| Planned
|===

For a detailed description of the features above, refer to the xref:doc/architecture.adoc[Architecture] page.

== Architecture

The xref:doc/architecture.adoc[Architecture] section of the docs covers the details of protecting your APIs with Kuadrant.

== xref:doc/getting-started.adoc[Getting started]

== User Guides

=== xref:doc/service-discovery-oas-configmap.adoc[HTTP routing rules from OpenAPI stored in a configmap]

=== xref:doc/service-discovery-oas-service.adoc[HTTP routing rules from OpenAPI served by the service]

=== xref:doc/service-discovery-path-match.adoc[HTTP routing rules with path matching]

=== xref:doc/authn-api-key.adoc[AuthN based on API key]

=== xref:doc/authn-oidc.adoc[AuthN based on OpenID Connect]

=== xref:doc/rate-limit.adoc[Rate limiting]

== Contributing

The xref:doc/development.adoc[Development guide] describes how to build the kuadrant controller and how to test your changes before submitting a patch or opening a PR.

== Licensing

This software is licensed under the https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0 license].

See the LICENSE and NOTICE files that should have been provided along with this software for details.
