apiVersion: networking.kuadrant.io/v1beta1
kind: API
metadata:
  name: api-sample
spec:
  hosts:
    - test.com
  operations:
    - name: get_pets
      id: get_pets
      path: /pets
      method: GET
      backendServerName: myserver1
    - name: create_pet
      id: create_pet
      path: /pets
      method: POST
      backendServerName: myserver1
  backendServers:
    - name: myserver1
      serviceRef:
        name: echo-api
        namespace: default
        path: /api1/
        port: 8080
