[package]
name = "limitador-server"
version = "0.4.0"
authors = ["David Ortiz <z.david.ortiz@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
limitador = { path = "../limitador", features = ['infinispan_storage'] }
tokio = { version = "0.2", features = ["full"] }
thiserror = "1.0"
tonic = "0.3"
prost = "0.6"
prost-types = "0.6"
serde_yaml = "0.8"
log = "0.4"
env_logger = "0.8"
url = "2.2"
actix-web = "3"
actix-rt = "1"
paperclip = { version = "0.5", features = ["actix"] }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-build = "0.2"
