# permissions for end users to edit services.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-editor-role
rules:
- apiGroups:
  - authorino.3scale.net
  resources:
  - authconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
- apiGroups:
  - authorino.3scale.net
  resources:
  - authconfigs/status
  verbs:
  - get
