[package]
name = "limitador"
version = "0.2.0"
authors = ["David Ortiz <z.david.ortiz@gmail.com>"]
license = "Apache-2.0"
description = "Rate limiter."
homepage = "https://github.com/kuadrant/limitador"
repository = "https://github.com/kuadrant/limitador"
documentation = "https://docs.rs/limitador"
edition = "2018"

# We make redis and infinispan optional to be able to compile for wasm32.
[features]
default = ["redis_storage"]
redis_storage = ["redis", "r2d2", "tokio"]
infinispan_storage = ["infinispan", "reqwest", "openssl"]

[dependencies]
ttl_cache = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
futures = "0.3"
async-trait = "0.1.41"
cfg-if = "1.0"
prometheus = "0.10"
lazy_static = "1.4"

# Optional dependencies
redis = { version = "0.17", optional = true, features = ["connection-manager"] }
r2d2 = { version = "0.8", optional = true }
tokio = { version = "0.2", optional = true, features = ["rt-core", "macros", "time"] }
infinispan = { version = "0.2", optional = true }
reqwest = { version = "0.10", optional = true }

# reqwest dependency. Needed here to avoid problems when compiling
openssl = { version = "0.10.34", optional = true, features = ["vendored"] }

[dev-dependencies]
serial_test = "0.5"
criterion = "0.3"
paste = "1.0"
rand = "0.7"
tokio = { version = "0.2", features = ["rt-core", "macros", "time"]  } # wasm_storage tests use tokio::test

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
