---
name: Command Testing

on: pull_request

jobs:
  install:
    name: Run kuadrantctl install
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.1
          config: utils/kind/cluster.yaml
          cluster_name: kuadrant-local
          wait: 120s
      - name: Check cluster info
        run: |
          kubectl cluster-info dump
      - name: build
        run: |
          make install
      - name: run command
        run: |
          kuadrantctl install
