apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
spec:
  template:
    spec:
      containers:
      - name: envoy
        volumeMounts:
        - name: authorino-ca-cert
          subPath: ca.crt
          mountPath: /etc/ssl/certs/authorino-ca-cert.crt
          readOnly: true
      volumes:
      - name: authorino-ca-cert
        secret:
          defaultMode: 420
          secretName: authorino-ca-cert
