apiVersion: authorino.3scale.net/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
spec:
  hosts:
    - talker-api
  identity:
    - name: friends
      apiKey:
        labelSelectors:
          authorino.3scale.net/managed-by: authorino
          group: friends
      credentials:
        in: authorization_header
        keySelector: APIKEY
  metadata:
    - name: echo-api-get
      http:
        endpoint: http://talker-api.authorino.svc.cluster.local:3000/metadata?encoding=text/plain&original_path={context.request.http.path}
        method: GET
        sharedSecretRef:
          name: talker-api-protection-secret
          key: echo-metadata-shared-auth
        credentials:
          in: authorization_header
          keySelector: Bearer
    - name: echo-api-post-form
      http:
        endpoint: http://talker-api.authorino.svc.cluster.local:3000/metadata?encoding=form-data
        method: POST
        bodyParameters:
          - name: original_path
            valueFrom:
              authJSON: context.request.http.path
          - name: my_str
            value: foo
          - name: my_num
            value: 123
          - name: my_bool
            value: true
          - name: my_arr
            value: ["a", "b", "c"]
          - name: my_obj
            value:
              a_prop: "a value"
    - name: echo-api-post-json
      http:
        endpoint: http://talker-api.authorino.svc.cluster.local:3000/metadata?encoding=json
        method: POST
        contentType: application/json
        bodyParameters:
          - name: original_path
            valueFrom:
              authJSON: context.request.http.path
          - name: my_str
            value: foo
          - name: my_num
            value: 123
          - name: my_bool
            value: true
          - name: my_arr
            value: ["a", "b", "c"]
          - name: my_obj
            value:
              a_prop: "a value"
  response:
    - name: echo-api-metadata
      json:
        properties:
          - name: get-request
            valueFrom:
              authJSON: auth.metadata.echo-api-get
          - name: post-request-form
            valueFrom:
              authJSON: auth.metadata.echo-api-post-form
          - name: post-request-json
            valueFrom:
              authJSON: auth.metadata.echo-api-post-json
---
apiVersion: v1
kind: Secret
metadata:
  name: talker-api-protection-secret
stringData:
  echo-metadata-shared-auth: 7f6fcf4961b979cd703e6c396d1378e282b109991344a97c2ad4d785eece3d54
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: friend-1-api-key-1
  labels:
    authorino.3scale.net/managed-by: authorino
    group: friends
stringData:
  api_key: ndyBzreUzF4zqDQsqSPMHkRhriEOtcRx
type: Opaque
