apiVersion: authorino.3scale.net/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
spec:
  hosts:
    - talker-api
  identity:
    - name: authorized-service-accounts
      kubernetes:
        audiences:
          - talker-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-token-issuer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-token-issuer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # it's just for the demo :-)
subjects:
- kind: ServiceAccount
  name: sa-token-issuer
  namespace: ${AUTHORINO_NAMESPACE}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-consumer
