apiVersion: authorino.3scale.net/v1beta1
kind: AuthConfig
metadata:
  name: talker-api-protection
spec:
  hosts:
    - talker-api
  identity:
    - name: keycloak
      oidc:
        endpoint: http://keycloak:8080/auth/realms/kuadrant
  authorization:
    - name: email-verified-only
      json:
        rules:
          - selector: "auth.identity.email_verified"
            operator: eq
            value: "true"
