---
apiVersion: v1
kind: Service
metadata:
  annotations:
    discovery.kuadrant.io/scheme: "http"
    discovery.kuadrant.io/api-name: "petstore"
    discovery.kuadrant.io/tag: "production"
    discovery.kuadrant.io/port: api
    discovery.kuadrant.io/oas-path: "/openapi"
    discovery.kuadrant.io/oas-port: openapi
    discovery.kuadrant.io/oas-configmap: petstore-oas
  labels:
    discovery.kuadrant.io/enabled: "true"
    app: petstore
  name: petstore
spec:
  ports:
  - name: api
    port: 8080
    targetPort: 8080
  - name: openapi
    port: 9090
    targetPort: 9090
  selector:
    app: petstore
