---
openapi: "3.0.0"
info:
  title: "Petstore Service"
  version: "1.0.0"
servers:
  - url: https://petstore.swagger.io/v1
paths:
  /pets:
    get:
      operationId: "getPets"
      responses:
        405:
          description: "invalid input"
